name: Create and Deploy Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: lts/*
          cache: npm
      - run: npm install && mkdir -p ./bin
      - run: npm run package
      - run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: ${{ env.VERSION }}
          draft: true
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bin/valinor-theme.vsix
          asset_name: valinor-theme.vsix
          asset_content_type: application/octet-stream

  deploy:
    runs-on: ubuntu-latest
    needs: create_release
    if: github.event.release.draft == false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: lts/*
          cache: npm
      - run: npm install
      - env:
          VSCE_PUBLISHER_TOKEN: ${{ secrets.VSCE_PUBLISHER_TOKEN }}
        run: npm run vsce-publish -- -p $VSCE_PUBLISHER_TOKEN
